refactor: simplify function signatures and improve formatting across components

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -13,25 +13,26 @@ else
 fi
 
 echo ""
-echo "Step 2: 🚀 Running npm run build"
-if ! npm run build; then
-  echo "❌ Error in npm run build. Please fix the errors before continuing."
-  exit 1
-fi
-
-echo ""
-echo "Step 3: 🚀 Running npm run lint"
+echo "Step 2: 🚀 Running npm run lint"
 if ! npm run lint; then
   echo "❌ Error in npm run lint. Please check your code."
   exit 1
 fi
 
 echo ""
-echo "Step 4: 🚀 Running npm run format"
+echo "Step 3: 🚀 Running npm run format"
 if ! npm run format; then
   echo "❌ Error in npm run format. Please check your code."
   exit 1
 fi
+
+echo ""
+echo "Step 4: 🚀 Running npm run build"
+if ! npm run build; then
+  echo "❌ Error in npm run build. Please fix the errors before continuing."
+  exit 1
+fi
+
 
 # echo ""
 # echo "Step 5: 🚀 Running npm run test..."
